service:
  name: io-ts-serverless-handler-example

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    minimumCompressionSize: 1024 # Enable gzip compression for responses > 1 KB
  environment:
    AWS_NODEJS_CONNECTION_REUSE_ENABLED: 1

functions:
  listProducts:
    handler: handler.listProducts
    events:
      - http:
          method: get
          path: products
  getProduct:
    handler: handler.getProduct
    events:
      - http:
          method: get
          path: products/{id}
